authors: [HaloInverse, IDragonfire, Klezst, Magik, Nijikokun, N3X15, RchGrav]
depend: [WorldEdit, Vault]
description: Provides command based shops with dynamic pricing.
main: dynamicmarket.core.DynamicMarket
name: DynamicMarket
version: 0.1 Dragon
commands:
    shop:
       aliases: dshop
       description: Accesses the shop command system.
       usage: |
              /<command>
              /<command> help <topic/command>
              /<command> <itemid>
              /<command> <subcommand> <args>